# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#run rake secret twice and replace this key
development:
  secret_key_base: 8025c4cbdd17f5e4e3f3185902fe1f59229a2308f4752500c27005f1c5981daa492ce082e0482cd698f7736a4abec9c5938b565d27ec1e01a5c08c667f828fac

#run rake secret twice and replace this key
test:
  secret_key_base: b8cb70962f66a957e50e02cdbac2bfdc975514568a06869dedfcef8394dc418a803ad668188b1d9bc95e9692b8a1cdf3892964da3a16535c1a4170bd28aca3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
