# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = AdminUser.new
user.name = 'Dheeraj'
user.email = 'dheeraj@surabhilabs.in'
user.password = 'charge13'
user.password_confirmation= 'charge13'
user.save!

user = AdminUser.new
user.name = 'Sudhakar'
user.email = 'sudhakar@surabhilabs.in'
user.password = 'charge13'
user.password_confirmation= 'charge13'
user.save!StudentUser.create!([
  {email: "sudhakar@sudh.com", encrypted_password: "$2a$10$mp/C20N1nZLP.dUQZJN4vOQzRdD8K4UAvPYd4dKpTK3gFn7y1DhQy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-04-15 17:07:04", last_sign_in_at: "2015-04-15 17:00:56", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", name: "Sudhakar G", last_viewed_lecture: "-introduction-video"},
  {email: "asdfkj@asdfa.com", encrypted_password: "$2a$10$9v4VNgXzDn/fpUN1yKFsUuEsBv5s1GEOp3d6zcjBZuOaOtOIj2Bj.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-04-15 18:15:46", last_sign_in_at: "2015-04-15 18:15:46", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", name: "kljflasj", last_viewed_lecture: "-introduction-video"},
  {email: "asdf@asdf.com", encrypted_password: "$2a$10$Imxz.ukxp63qjR92Oyj55uPJWlZ5xxth5N0j5Xu.9XbR3B/Qs89sq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2015-04-16 18:44:58", last_sign_in_at: "2015-04-16 18:22:15", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", name: "asdf", last_viewed_lecture: "-routes"}
])
AdminUser.create!([
  {email: "dheeraj@surabhilabs.in", encrypted_password: "$2a$10$7KUr0bE6J1eU7Ipgi.2Zu.bFn6P4ndrLmufg3i54xq9alSGEmUP3u", remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, name: "Dheeraj"},
  {email: "sudhakar@surabhilabs.in", encrypted_password: "$2a$10$UqBvYUChyD0kDR7Db8Y9YOVLNLciX6ZfBlcr4ArW42Fu9JVFL621O", remember_created_at: nil, sign_in_count: 10, current_sign_in_at: "2015-04-16 19:42:09", last_sign_in_at: "2015-04-16 18:43:34", current_sign_in_ip: "10.0.2.2", last_sign_in_ip: "10.0.2.2", name: "Sudhakar"}
])
Lesson.create!([
  {section_id: 3, name: "Lets get rolling!!", permalink: "-lets-get-rolling", position: 3, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" allowfullscreen src=\"/assets/3.webm\" width=\"700\"></iframe></p>"},
  {section_id: 4, name: "Functioning website", permalink: "-functioning-website", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" allowfullscreen src=\"/assets/4.webm\" width=\"700\"></iframe></p>"},
  {section_id: 5, name: "What is MVC all about??", permalink: "-what-is-mvc-all-about", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/5.webm\" width=\"700\" allowfullscreen autoplay=false></iframe></p>"},
  {section_id: 1, name: "Introduction", permalink: "-introduction-video", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"620\" scrolling=\"no\" src=\"/assets/1.webm\" width=\"700\" allowfullscreen></iframe></p>\r\n"},
  {section_id: 10, name: "Lab", permalink: "-pictures-lab", position: 2, visible: true, body: "<p>As explained in the video, make changes in the code to enable<em><strong>&nbsp;picture uploading</strong></em>&nbsp;feature.</p>\r\n\r\n<p><span style=\"color:rgb(255, 0, 0)\">Its really important you follow commands right when adding picture column to database either follow the command in Video or use this.&nbsp;</span></p>\r\n\r\n<p><span style=\"color:rgb(255, 0, 0)\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;$rails generate migration add_picture_to_ads&nbsp;picture:string</span></p>\r\n\r\n<p><span style=\"color:rgb(255, 0, 0)\">Notice the new column you are adding should always be a lower case &quot;p&quot; in picture. Column names in rails always are in lower case</span></p>\r\n\r\n<p><span style=\"color:rgb(255, 0, 0)\">&nbsp;$rake db:migrate</span></p>\r\n\r\n<p>Now continue the lab following the video</p>\r\n\r\n<p>Show the&nbsp;results to your mentor.</p>\r\n\r\n<p>Like carrierwave, there are alot of gems available to us, which provide readymade features. Explore the internet and search for gems, which are of interest to you.</p>\r\n"},
  {section_id: 13, name: "Magic of CRUD", permalink: "-magic-of-crud", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/6.webm\" width=\"700\" allowfullscreen></iframe></p>\r\n"},
  {section_id: 6, name: "Routes", permalink: "-routes", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/7.webm\" width=\"700\" allowfullscreen></iframe></p>\r\n"},
  {section_id: 11, name: "Form validations", permalink: "-form-validations", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" allowfullscreen src=\"/assets/12.webm\" width=\"700\"></iframe></p>"},
  {section_id: 8, name: "Basics of HTML and CSS", permalink: "-basics-of-html-and-css", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/9.webm\" allowfullscreen width=\"700\"></iframe></p>\r\n"},
  {section_id: 9, name: "Lets Dive into the code", permalink: "-lets-dive-into-the-code", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" allowfullscreen scrolling=\"no\" src=\"/assets/10.webm\" width=\"700\"></iframe></p>"},
  {section_id: 11, name: "Validations Lab", permalink: "-validations-lab", position: 2, visible: true, body: "<p><strong>As explained in the video, add validations to the form fields.</strong></p>\r\n"},
  {section_id: 12, name: "Categories Lab", permalink: "-categories-lab", position: 2, visible: true, body: "<p><span style=\"font-family: helvetica;\">Add Categories to your Ads. Below are the highlevel steps to accomplish the task.</span></p>\r\n<p><span style=\"font-family: helvetica;\">1. Generate a model for <strong>Category</strong></span></p>\r\n<p><span style=\"font-family: helvetica;\">2. Add entries into <strong>Category</strong> table.</span></p>\r\n<p><span style=\"font-family: helvetica;\">3. Add the <em>category_id</em> column to the <em><strong>ads</strong></em> table </span></p>\r\n<p><span style=\"font-family: helvetica;\">4. Link the models Ad and Category.</span></p>\r\n<p><span style=\"font-family: helvetica;\">5. Assign a category id for the saved ads. </span></p>\r\n<p><span style=\"font-family: helvetica;\">6. Create dropdown for Category.</span></p>\r\n<p><span style=\"font-family: helvetica;\">7. Display Category name in <strong>ad</strong> by changing show.html </span></p>\r\n<p><span style=\"font-family: helvetica;\">8. Whitelist category id</span></p>\r\n          "},
  {section_id: 12, name: "Adding categories to the ads", permalink: "-adding-categories-to-the-ads", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" allowfullscreen scrolling=\"no\" src=\"/assets/13.webm\" width=\"700\"></iframe></p>"},
  {section_id: 7, name: "Ruby Lab", permalink: "-ruby-lab", position: 2, visible: true, body: "<p>Follow along while watching the video</p>\r\n\r\n<p>Go to <em><strong>rails console</strong></em> and experiment with Ruby,</p>\r\n\r\n<p><strong>1). Create a String; </strong></p>\r\n\r\n<p>irb(main):001:0&gt; <span style=\"color:#008000\"><em><strong>a = &#39;Hello&#39;</strong></em></span></p>\r\n\r\n<p>irb(main):002:0&gt; <span style=\"color:#008000\"><em><strong>a.length</strong></em></span></p>\r\n\r\n<p><strong>2). Concatenate a String</strong></p>\r\n\r\n<p>irb(main):003:0&gt; <span style=\"color:#008000\"><em><strong>puts a + &quot; world&quot;</strong></em></span></p>\r\n\r\n<p><strong>3). Define a method called <span style=\"color:#0000ff\">wishUser</span></strong></p>\r\n\r\n<p><strong>Follow the video for steps. </strong></p>\r\n\r\n<p><strong>4). Define a method called <span style=\"color:#ff00ff\"><span style=\"color:#0000ff\">wishUser,</span></span> which takes default parameters</strong></p>\r\n\r\n<p><strong>Follow the video for steps. </strong></p>\r\n\r\n<p><strong>5). Define an array and play with it</strong></p>\r\n\r\n<p>irb(main):004:0&gt; <span style=\"color:#008000\"><em><strong>a = [1,2,3,45,6]</strong></em></span></p>\r\n\r\n<p>irb(main):004:0&gt; <span style=\"color:#008000\"><em><strong>a.first</strong></em></span></p>\r\n\r\n<p>irb(main):004:0&gt; <span style=\"color:#008000\"><em><strong>a.last</strong></em></span></p>\r\n\r\n<p>irb(main):004:0&gt; <span style=\"color:#008000\"><em><strong>a.empty?</strong></em></span></p>\r\n\r\n<p>irb(main):004:0&gt;<span style=\"color:#008000\"><em><strong> a.sort</strong></em></span></p>\r\n\r\n<p>irb(main):004:0&gt; <span style=\"color:#008000\"><em><strong>a.sort!</strong></em></span></p>\r\n\r\n<p><strong>6). Define a hash </strong><strong> as explained in video</strong></p>\r\n\r\n<p><strong>7). Play around with blocks as explained in Video</strong></p>\r\n\r\n<p><strong>8). Write few loops.</strong></p>\r\n\r\n<p><span style=\"color:#800000\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;5.times</span><span style=\"color:#000000\"> </span><span style=\"color:#000000\">{</span><span style=\"color:#000000\"> print </span><span style=\"color:#000000\">(</span><span style=\"color:#800000\">&quot;xxx&quot;</span><span style=\"color:#000000\">)</span><span style=\"color:#000000\"> </span><span style=\"color:#000000\">}</span></p>\r\n"},
  {section_id: 6, name: "Routes Lab", permalink: "-routes-lab", position: 2, visible: true, body: "<p>As explained in the video, create a new working URL&nbsp;which looks like below</p>\r\n\r\n<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&quot;http://&lt;your-c9-io-name&gt;.c9.io/<span style=\"color:rgb(0, 128, 0)\">testpath&quot;</span></strong>&nbsp;</p>\r\n\r\n<p>Show the result to the mentor.</p>\r\n"},
  {section_id: 7, name: "Ruby - The Language", permalink: "-ruby-the-language", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/8.webm\" allowfullscreen width=\"700\"></iframe></p>\r\n"},
  {section_id: 10, name: "Lets add images!!", permalink: "-lets-add-images", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" allowfullscreen src=\"/assets/11.webm\" width=\"700\"></iframe></p>"},
  {section_id: 2, name: "What is the application architecture?", permalink: "-what-is-the-application-architecture", position: 1, visible: true, body: "<p><iframe frameborder=\"0\" height=\"520\" scrolling=\"no\" src=\"/assets/2.webm\" allowfullscreen width=\"700\"></iframe></p>"},
  {section_id: 4, name: "Lab 2", permalink: "-lab-2", position: 2, visible: true, body: "<p>Start the rails server using the button <em><strong>&quot;Run Project&quot; .</strong></em><strong> </strong>This is equivalent to running &quot;rails server&quot;command.</p>\r\n\r\n<p>Since we are using a virtual workspace, &quot;rails server&quot; will not work as shown in the video.</p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/VapzNZt.png\" style=\"height:512px; width:800px\" /></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>You should see this.</strong></p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/dgtL828.png\" style=\"height:512px; width:800px\" /></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Click on the URL, you should see this</strong></p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/OAoT6FM.png\" style=\"height:512px; width:800px\" /></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>In the URL change to </strong></p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/LdIFos0.png\" style=\"height:662px; width:800px\" /></strong></p>\r\n\r\n<p><strong>When you add <span style=\"color:rgb(255, 0, 0)\"><em>/ads</em></span> then you should see a page like below</strong></p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/ABcojCC.png\" style=\"height:662px; width:800px\" /></strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>If you have added <em><strong>ads</strong> </em>as part of the previous lab, those entries will be listed.</p>\r\n\r\n"},
  {section_id: 3, name: "Lab", permalink: "-lab", position: 4, visible: true, body: "<p>Its really important you follow commands right. Lowercase and Upper case. When you scaffold you must give rails generate scaffold &quot;Ad&quot; without failure..Notice that it is, Captial &quot;A&quot; and small &quot;d&quot;</p>\r\n\r\n<p>$<strong><span style=\"color:#ff0000\"><em> rails generate scaffold Ad title:string description:text name:string email:string phone:string location:string</em></span></strong></p>\r\n\r\n<p><strong><img src=\"http://i.imgur.com/zYPniYN.png\" style=\"height:512px; width:800px\" /></strong></p>\r\n\r\n<p><strong>Everything generated above will be discussed in detail in the future lectures.</strong></p>\r\n\r\n<p><strong>Commit to databased using:</strong></p>\r\n\r\n<p>$<em><span style=\"color:#ff0000\"><strong> rake db:migrate</strong></span></em></p>\r\n\r\n<p><strong>To see the changes we just made, enter into <em>rails console</em> with the below command</strong></p>\r\n\r\n<p>$<span style=\"color:#ff0000\"><em><strong> rails console</strong></em></span></p>\r\n\r\n<p>Execute the following commands inside the rails console one after the other and observe the results.</p>\r\n\r\n<p>irb(main):001:0&gt;<span style=\"color:#008000\"><strong><em> Ad.all</em></strong></span></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>irb(main):002:0&gt;<span style=\"color:#008000\"><strong><em> advar = Ad.new</em></strong></span></p>\r\n\r\n<p>irb(main):003:0&gt;<span style=\"color:#008000\"><strong><em> advar.title = &#39;iphone&#39;</em></strong></span></p>\r\n\r\n<p>irb(main):004:0&gt;<span style=\"color:#008000\"><strong><em> advar.description = &#39;in good condition&#39;</em></strong></span></p>\r\n\r\n<p>irb(main):005:0&gt;<span style=\"color:#008000\"><strong><em> advar.name = &quot;Ramu&quot;</em></strong></span></p>\r\n\r\n<p>irb(main):006:0&gt;<span style=\"color:#008000\"><strong><em> advar.email = &quot;ramu@gmail.com&quot;</em></strong></span></p>\r\n\r\n<p>irb(main):007:0&gt;<span style=\"color:#008000\"><strong><em> advar.phone = &quot;955060338&quot;</em></strong></span></p>\r\n\r\n<p>irb(main):008:0&gt;<span style=\"color:#008000\"><strong><em> advar.location = &quot;Nuzividu&quot;</em></strong></span></p>\r\n\r\n<p>irb(main):009:0&gt;<strong><span style=\"color:#008000\"><em> advar.save</em></span></strong></p>\r\n\r\n<p><strong>Create more ads like above and show the mentor.</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n"},
  {section_id: 3, name: "Few Basic linux commands", permalink: "-few-basic-linux-commands", position: 2, visible: true, body: "<p><strong>References:&nbsp;</strong></p>\r\n\r\n<p>http://mally.stanford.edu/~sr/computing/basic-unix.html</p>\r\n\r\n<p>http://www.tecmint.com/useful-linux-commands-for-newbies/</p>\r\n\r\n<p>http://www.comptechdoc.org/os/linux/usersguide/linux_ugbasics.html</p>\r\n\r\n<p>&nbsp;</p>\r\n"},
  {section_id: 3, name: "Setup your cloud workspace", permalink: "-setup-your-cloud-workspace", position: 1, visible: true, body: "<p>Through out this workshop, you will be developing your website in a workspace provisioned on the Cloud.</p>\r\n<p>Here are the steps for getting started with the cloud development environment:</p>\r\n<ul>\r\n<li><a href=\"https://c9.io/web/sign-up/free\" style=\"font-size: inherit; color: #002f72;\" target=\"_blank\">Sign up for a free account at Cloud9</a></li>\r\n</ul>\r\n<p><img height=\"669\" src=\"http://i.imgur.com/USWggX4.png\" target=\"[object Object]\" type=\"saveimage\" width=\"800\"/></p>\r\n<ul>\r\n<li><span style=\"font-size: 1em; line-height: 1.6em;\">Click on the &quot;Create Workspace&quot; on the left and then select on &quot;Create a new workspace&quot; </span></li>\r\n</ul>\r\n<p><span style=\"font-size: 1em; line-height: 1.6em;\"><img height=\"512\" src=\"http://i.imgur.com/Ag6tcnF.png\" target=\"[object Object]\" type=\"saveimage\" width=\"800\"/></span></p>\r\n<ul>\r\n<li><span style=\"color: #070707; font-family: Georgia, serif; font-size: 18px; line-height: 27px; background-color: #f9f9f9;\">Create a workspace called olx. </span><span style=\"color: #070707; font-family: Georgia, serif; font-size: 18px; line-height: 27px; background-color: #f9f9f9;\"> , and select the </span><span style=\"color: #070707; font-family: Georgia, serif; font-size: 18px; line-height: 27px; background-color: #f9f9f9;\">icon for <strong>Ruby on Rails</strong></span></li>\r\n<li><span style=\"line-height: 1.6; font-size: 1em;\">Click “Create”</span></li>\r\n</ul>\r\n<p><span style=\"line-height: 1.6; font-size: 1em;\"><img height=\"512\" src=\"http://i.imgur.com/ePvI8Oy.png\" target=\"[object Object]\" type=\"saveimage\" width=\"800\"/></span></p>\r\n<ul>\r\n<li><span style=\"line-height: 1.6; font-size: 1em;\">On the left, select on the tab called <em><strong>olx</strong> </em>and then Click <em><strong>&quot;Start Editing&quot; .</strong></em><strong> </strong>Refresh your page once, if you do not see the <em><strong>&quot;Start Editing&quot;</strong></em> button.</span></li>\r\n</ul>\r\n<p><span style=\"line-height: 1.6; font-size: 1em;\"><img height=\"512\" src=\"http://i.imgur.com/TsxElho.png\" target=\"[object Object]\" type=\"saveimage\" width=\"800\"/></span></p>\r\n<ul>\r\n<li><span style=\"line-height: 1.6; font-size: 1em;\">After clicking on “Start editing”, a new tab will open up, that loads your workspace which looks like below. </span></li>\r\n</ul>\r\n<p><img height=\"512\" src=\"http://i.imgur.com/DoI04fY.png\" target=\"[object Object]\" type=\"saveimage\" width=\"800\"/></p>\r\n<p><strong>Make sure that you are able to see your workspace successfully, before moving on to the next chapter.</strong></p>\r\n<p>Call your mentor and resolve the issues if there are any. </p>\r\n<p></p>"}
])
Section.create!([
  {name: "Introduction to Ruby on Rails", position: 1, visible: true},
  {name: "Application Architecture", position: 2, visible: true},
  {name: "Creating the website", position: 3, visible: true},
  {name: "Functioning Website", position: 4, visible: true},
  {name: "Magic of MVC", position: 5, visible: true},
  {name: "Understanding the CRUD Operations", position: 6, visible: true},
  {name: "Routes and URL Mappings", position: 7, visible: true},
  {name: "Basics of Ruby", position: 8, visible: true},
  {name: "HTML and CSS Overview", position: 9, visible: true},
  {name: "Understanding the generated code", position: 10, visible: true},
  {name: "Adding Pictures", position: 11, visible: true},
  {name: "Adding Validations", position: 12, visible: true},
  {name: "Adding Categories", position: 13, visible: true}
])
